Create React Redux Assignment
madan-webonise/React-ReduxAssignment pull request #1
Opened 2018-04-19 14:10 UTC by madan-webonise

- Assignment

2018-04-20 07:08 UTC, swapnil-webonise requested changes

2018-04-20 07:08 UTC, swapnil-webonise commented on my-app/package.json
> +}
Configure your editor for adding a new line.

2018-04-20 07:08 UTC, swapnil-webonise commented on my-app/src/App.js
> +import './assets/styles/layout.css';
Use alias for importing dependencies

2018-04-20 07:08 UTC, swapnil-webonise commented on my-app/src/App.js
> +class App extends Component {
give component name like AppComponent

2018-04-20 07:23 UTC, owais-webonise requested changes
Needs Improvement

2018-04-20 07:23 UTC, owais-webonise commented on my-app/src/App.js
> +//delete functionality has to be done
Remove comments

2018-04-20 07:23 UTC, owais-webonise commented on my-app/src/TodoList.js
> +      arrayFromParent: this.props.displayList
Change name of array, use proper name convention

2018-04-20 07:23 UTC, owais-webonise commented on my-app/src/TodoList.js
> +export default TodoList;
Add default props

2018-05-16 10:24 UTC, owais-webonise approved these changes

2018-05-22 11:21 UTC, merged